http:
  Port: "8081"
  Host: "localhost"
  
systemapi:
  retrieve_url: "http://ms3empcontactapi.us-e2.cloudhub.io/EmployeeRecord"
  delete_url: "http://ms3empcontactapi.us-e2.cloudhub.io/EmployeeRecord",
  insert_url: "http://ms3empcontactapi.us-e2.cloudhub.io/EmployeeRecord",
  update_url: "http://ms3empcontactapi.us-e2.cloudhub.io/EmployeeRecord"
  
